# syntax=docker/dockerfile:1.4.1
FROM nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04

ENV DISPLAY=$DISPLAY
ENV DEBIAN_FRONTEND=noninteractive

COPY packages.txt /tmp/packages.txt

RUN sed -i 's|http://archive.ubuntu.com/ubuntu/|http://ftp.jaist.ac.jp/pub/Linux/ubuntu/|g' /etc/apt/sources.list && \
    sed -i 's|http://security.ubuntu.com/ubuntu|http://ftp.jaist.ac.jp/pub/Linux/ubuntu/|g' /etc/apt/sources.list && \
	apt-get update \
	&& apt-get install -y --no-install-recommends \
	python3 \
	python3-pip \
	python3-venv \
	apt-utils \
	gcc \
	curl \
	build-essential \
	sudo \
	openssh-client \
	# 日本語環境
	task-japanese \
	locales \
	fonts-takao \
	task-japanese-desktop \
	ibus-kkc \
    # packages.txt
    && xargs -a /tmp/packages.txt apt-get install -y --no-install-recommends \
	# clean up
	&& apt-get autoremove -y \
	&& apt-get clean -y \
	&& rm -rf /var/lib/apt/lists/*

RUN sudo ln -s /usr/bin/python3 /usr/local/bin/python

# 日本語設定
RUN sed -i -E 's/# (ja_JP.UTF-8)/\1/' /etc/locale.gen \
	&& locale-gen
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
# JST
RUN ln -fs /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata

ARG WORKDIR
ENV PATH=${WORKDIR}/vendor/bin:$PATH \
	PYTHONPATH=${WORKDIR}/vendor/bin:${WORKDIR} \
	PYTHONUSERBASE=${WORKDIR}/vendor

WORKDIR ${WORKDIR}

# Libraries used only when developing
RUN pip install --upgrade pip;\
	pip install --no-cache-dir \
	autopep8 \
	flake8 \
	pytest

# Create the user
ARG USERNAME
ARG HOMEDIR
ARG USERID
ARG GROUPID
RUN <<-EOF
	echo "Create User = ${USERID}. Group = ${GROUPID}"
	groupadd -g ${GROUPID} ${USERNAME}
	useradd -m -s /bin/bash -d ${HOMEDIR} -k /etc/skel -u ${USERID} -g ${GROUPID} ${USERNAME}
	echo ${USERNAME} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME}
	chmod 0440 /etc/sudoers.d/${USERNAME}
	chown -R ${USERNAME}:${USERNAME} ${HOMEDIR}
EOF
USER ${USERNAME}

# Rust(for DeepFilterNet)
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="$PATH:${HOMEDIR}/.cargo/bin"
