blank_issues_enabled: false
contact_links: []
issue_templates:
  - name: サポート質問
    description: サポートが必要な場合はこちらからお問い合わせください。
    body: |
      ### 問題の詳細
      ここに問題の詳細を記入してください。

      ### 再現手順
      1.
      2.
      3.

      ### 期待される結果
      ここに期待される結果を記入してください。

      ### 実際の結果
      ここに実際の結果を記入してください。

      ### その他の情報
      ここにその他の情報を記入してください。
